### ISSUE TITLE
Checklist of files to eventually include

### ISSUE THREAD

**Issue by jploveless** [jploveless/relax_disloc#2]
- [ ] Relax input files for parameter space forward models
- [ ] Relax input file for postseismic-interseismic combo
- [ ] Markdown in Chi-Chi that points to Relax repo files
